<?php

const ALUMNO = "ALUMNO";
const ALUM_ID = "ALUM_ID";
const ALUM_NOMBRE = "ALUM_NOMBRE";
const ALUM_APELLIDO_P = "ALUM_APELLIDO_P";
const ALUM_APELLIDO_M = "ALUM_APELLIDO_M";
const ALUM_MATRICULA = "ALUM_MATRICULA";
const ALUM_CARRERA = "ALUM_CARRERA";
